name: CI

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Precommit-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
          pip3 install -e .

      - name: Run pre-commit
        run: |
          python3 continuous_integration/precommit.py

      - name: Install MicroPython
        uses: BrianPugh/install-micropython@v1
        with:
          reference: v1.20.0

      - name: Run tests
        run: |
          ./tests/run_all_tests.sh
